### ISSUE TITLE
Using line-comments as regions

### ISSUE THREAD

**Issue by StreakyCobra** [purcell/mmm-mode#59]
Hi,

I'm trying to configure `mmm-mode` to use `markdown-mode` for the formatting of `rust` documentation comments, as this has been [defined as a by convention](https://doc.rust-lang.org/book/documentation.html#documenting-source-code). Here is a code example:

```rust
/// Constructs a new `Rc<T>`.
///
/// # Examples
///
/// ```
/// use std::rc::Rc;
///
/// let five = Rc::new(5);
/// ```
pub fn new(value: T) -> Rc<T> {
    // implementation goes here
}
```

I had a look at some examples of `mmm-mode` classes I found, and I also read the whole `mmm-classes-alist` docstring. All my tries have been without succes for now.

Before spending more time trying to make it work, could you tell me if it is possible to make `mmm-mode` use line-comments for defining regions, and if yes, do you have some pointers to examples or relevant keywords?

Thanks in advance :-)

**Comment by dgutov** [comment]
It might be problematic: because either you include the `///` into the subregion (and the submode thinks the code is inside comments), or you create a subregion for each line inside the markdown example, avoiding the `///` pieces. but that might break some functionality in continuation lines. Or not, I don't know how rust-mode deals with them.

In short, it should be doable, but you might have to dig deeper into `mmm-mode` and how major modes work than you'd like. I don't have a good example to offer.

**Comment by StreakyCobra** [comment]
> or you create a subregion for each line inside the markdown example

I thought about this too, but I suppose this will loose the context information, like code block inbetween triple backquotes would be interpreted as markdown :-/

> In short, it should be doable, but you might have to dig deeper into mmm-mode and how major modes work than you'd like. I don't have a good example to offer.

It is the kind of answer I expected: there is no simple way. I've sadly not enough knowledge nor time to go deeper into this.

Thanks for the information anyway :-)
