### ISSUE TITLE
Thoughts on adding support for overlays-heavy, stateful major modes?

### ISSUE THREAD

**Issue by cpitclaudel** [purcell/mmm-mode#69]
Hi @purcell,

I'd like to add support for mmm to packages like [fstar-mode](https://github.com/FStarLang/fstar-mode.el) or [Proof General](https://github.com/ProofGeneral/PG/).  (As you may remember) PG already has some support for it, but it has suffered from a bad case of bitrot.

I've read through the docs, but there's one thing I'm unsure about: what are good heuristics for chosing what to make into the master mode? Should I teach fstar-mode to behave as a submode, or should I teach it to act as a major mode?

Also, how does syntax-ppss behave wrt mmm? If I call syntax-ppss from my fstar-mode code, will it ignore comment openers found in non-fstar-mode sections, for example?

**Comment by purcell** [comment]
My head's really not in `mmm-mode` enough to provide much guidance in this case, sorry. Generally `syntax-ppss` will be called by `mmm` in a context restricted to the submode region, but I know that weird things can happen if the submode's syntax functions try to be too clever.

Ideally there's no `master mode` and `submode`, because any two (or more) modes can co-exist in buffer subregions using `mmm-mode`, controlled entirely by the patterns in submode classes. So what you probably want is just to make sure that each of your major modes is a good citizen in terms of being a submode under `mmm`.

**Comment by dgutov** [comment]
I think the master mode is plainly the one that the beginning and end of the buffer belong to. But that's not a strict rule, probably.

> If I call syntax-ppss from my fstar-mode code, will it ignore comment openers found in non-fstar-mode sections, for example?

Depends on what code it's called from.

But if those comment openers are in a "submode", and the master mode interprets them as such, and the submode doesn't, you should probably use a new derived mode as the master, and set an `mmm-after-syntax-propertize-function` there which will apply punctuation syntax to them, like here: https://github.com/purcell/mmm-mode/blob/631e7f12d1641cb40e650134f35f2680a1a310a1/mmm-erb.el#L93-L98

**Comment by cpitclaudel** [comment]
Thanks @dgutov and @purcell :)
